[workspace]
members = ["crates/qform-sys", "crates/qform"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.92"

[workspace.dependencies]
bindgen = "0.72"
gmp-mpfr-sys = { version = "1.6", default-features = false }
optarith = { git = "https://github.com/mkorje/liboptarith", package = "optarith", default-features = false }
optarith-sys = { git = "https://github.com/mkorje/liboptarith", package = "optarith-sys" }
qform-sys = { path = "crates/qform-sys", default-features = false }
